services:
    sqlite-web:
        stdin_open: true
        tty: true
        ports:
            - 3000:8080
        volumes:
            - /DIR_DB:/data
        image: ghcr.io/coleifer/sqlite-web:latest
        command: /data/diabolik.db

